import { Link } from "react-router-dom";
import CustomButton from "../components/CustomButton";
import hero from "/assets/images/hero.jpg";

/**
 * Home Page
 *
 * This component renders the home page of StoryPath, featuring:
 * - A hero section with a welcome message and buttons for exploring or creating projects
 * - A features section highlighting StoryPath's functionalities like creating tours and adventures
 * - A dynamic background image (hero.jpg)
 *
 * Text for the hero and features sections was generated by ChatGPT. Uses CustomButton and React Router's Link for navigation.
 *
 * JSDoc comments above were generated by ChatGPT
 */
const Home = () => {
  return (
    <div
      className="relative min-h-screen bg-cover bg-center overflow-y-auto"
      style={{
        backgroundImage: `url(${hero})`,
      }}
    >
      {/* Content Section */}
      <div className="relative z-10 container mx-auto py-12 text-center h-full flex flex-col justify-center">
        {/* Hero Section */}
        <div className="mb-12">
          <h1 className="text-5xl font-bold text-white mb-4 text-shadow-md">
            Welcome to StoryPath
          </h1>
          <p className="text-lg text-white text-shadow-lg">
            Bring your stories to life with location-based experiences!
          </p>
          <p className="text-lg text-white mb-8 text-shadow-lg">
            Create and explore virtual museum exhibits, treasure hunts, and
            more.
          </p>

          <div className="flex justify-center space-x-4">
            {/* Explore Projects Button */}
            <Link to="/projects">
              <CustomButton
                label="Explore Projects"
                className="bg-accent text-white hover:bg-accent-dark py-2 rounded-lg"
              />
            </Link>

            {/* Create New Project Button */}
            <CustomButton
              label="Create New Project"
              className="bg-primary text-white hover:bg-primary-dark py-2 rounded-lg"
              to="/project/new"
            />
          </div>
        </div>

        {/* Features Section */}
        <div className="mt-12">
          <h2 className="text-2xl font-semibold text-white mb-6 text-shadow-md">
            What You Can Do with StoryPath
          </h2>

          <p className="text-lg text-white text-shadow-default mb-2">
            Create engaging tours, treasure hunts, and more!
          </p>
          <p className="text-lg text-white text-shadow-default mb-2">
            Design interactive experiences like museum and campus tours.
          </p>
          <p className="text-lg text-white text-shadow-default mb-2">
            Customize adventures to bring your stories to life.
          </p>
        </div>
      </div>

      {/* Fading Section to make sure the image fades naturally */}
      <div className="absolute inset-0 bg-gradient-to-b from-transparent to-background z-0"></div>
    </div>
  );
};

export default Home;

/*
  Text generated by ChatGPT was used in this home page for the following sections:
  - Hero Section: Headline and introductory paragraphs ("Bring your stories to life with location-based experiences!" etc.)
  - Features Section: "What You Can Do with StoryPath" and the descriptive points
*/
